---
title: "about"
---

This website serves as an example workflow using R to collect and clean ATP tennis data, and using that data to potentially make smarter decisions when striking a bet or bets.  Other tools like [Make](https://www.gnu.org/software/make/) and [Git](https://git-scm.com/) are used.  Make is used to build pipelines and join different tasks together, such as the collection and cleaning of data, as its name suggests it helps make or build things, while Git helps to manage all the different parts.

### collection

The collection of tennis data has been split into 3 sections, I walk through collecting [tournament data](tournament-data-collection.html), [match data](match-data-collection.html) and [player data](player-data-collection.html).   If we were to use this code interactively then we can just go after the individual player data either with code, or navigating to the website and just typing in values, so the tournament data and match data doesn't offer much value.  However, if this is to ever be fully automated, then it requires a pipeline; automation can help save time and allow you to focus on other valuable work which can be integrated later.  

### `make` pipeline

So the pipeline requires tournament data to tell us which tournaments are live, this helps us to find matches scheduled for _today_, and match data contains the players, whose data we require.

The [Makefile]() included used to build this website has a number of commands and operations, details of these can be found on the [make](make.html)

### `rmarkdown` website

This website is built using the `rmarkdown` package, developed by [Rstudio](), help pages can be found [here]().  `rmarkdown` uses the `knitr` package to help create dynamic documents.   What is a dynamic document?  A dynamic document is basically facilitates reproducibility, other users can recreate the document on their own machine (if they have access to the same data).  It also allows you to build entire websites (like this one) which can host content that changes over time, with little to no input from the creator once they scaffolded the website out.  This building can then be automated which means they can focus on developing other tools to help them.

The [todays matches](todays-matches.html) page shows the dynamic nature